server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WeatherWear
    username: root
    password: w@@3414078!!
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  #mail설정
  mail:
    host: smtp.naver.com
    port: 465
    username: et0709@naver.com
    password: w6978979
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버 인증을 활성화
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true #STARTTLS(암호화 프로토콜)를 활성화(메일 전송 중 데이터 암호화를 지원)

logging:
  level:
    org.springframework.security: DEBUG
